import type { NextPage } from 'next';
import Head from 'next/head';
import HomeLayout from '../components/Layouts/HomeLayout';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeLayout>Hello</HomeLayout>
    </div>
  );
};

export default Home;
