import type { NextPage } from 'next';
import Head from 'next/head';
import HomeLayout from '../components/Layouts/HomeLayout';
import DesktopView from '../components/UI/organisms/DesktopView';
import MobileView from '../components/UI/organisms/MobileView';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeLayout>
        <MobileView />
        <DesktopView />
      </HomeLayout>
    </div>
  );
};

export default Home;
